### ISSUE TITLE
Env variable to disable ipv6 for nginx

### ISSUE THREAD

**Issue by christophdb** [datamate-rethink-it/seafile-release#37]
Observed by one customer who had disabled ipv6. Nginx is not starting due to `listen [::]:80`. Therefore we need an environment variable to remove this...

**Comment by simonhammes** [comment]
I'll add an environment variable for this. 

Unfortunately I could not reproduce the problem.

I even tried disabling IPv6 on the host and for the Docker daemon using this [manual](https://www.laub-home.de/wiki/Docker_IPv6_deaktivieren) :shrug: 

---

Does the go fileserver also cause problems?

```bash
root@cf213af6594a:/opt/seafile# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      31/nginx: master pr 
tcp        0      0 127.0.0.11:39569        0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:8083          0.0.0.0:*               LISTEN      185/notification-se 
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      177/python3         
tcp6       0      0 :::80                   :::*                    LISTEN      31/nginx: master pr 
tcp6       0      0 :::8082                 :::*                    LISTEN      130/fileserver      
udp        0      0 127.0.0.11:58681        0.0.0.0:*                           -
```

**Comment by simonhammes** [comment]
I could reproduce the issue by disabling IPV6 inside `/etc/default/grub` and will PR a fix :+1:

**Comment by simonhammes** [comment]
> Does the go fileserver also cause problems?

Go checks IPV6 availability and does not try to listen on `::1` if it's not available :)
