### ISSUE TITLE
nfs in storage classes

### ISSUE THREAD

**Issue by christophdb** [datamate-rethink-it/seafile-release#38]
Currently it seems not possible to use the storage_classes file for nfs shares. 
The error message is:

- nfs in storage_classes ging nicht:
failed to run "seaf-server -t" [65280]
2024-10-30 12:28:42 ../common/seaf-utils.c(668): Failed to load json file: /opt/seafile/seafile_storage_classes.json
2024-10-30 12:28:42 seafile-session.c(248): Commits, fs and blocks should use different buckets or pools. Refuse to start server.
Error: failed to create ccnet session
Traceback (most recent call last):
  File "/scripts/cluster_start.py", line 73, in <module>
    main(parser.parse_args())
  File "/scripts/cluster_start.py", line 54, in main
    call('{} start'.format(get_script('seafile.sh')))
  File "/scripts/utils.py", line 70, in call
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-pro-server-11.0.14/seafile.sh start' returned non-zero exit status 1.

the storage class file looked like this:

```
[
    {
      "storage_id": "nfs",
      "name": "nfs",
      "is_default": true,
      "commits": {
        "backend": "fs",
        "dir": /opt/seafile/seafile-data"
      },
      "fs": {
        "backend": "fs",
        "dir": /opt/seafile/seafile-data"
      },
      "blocks": {
        "backend": "fs",
        "dir": /opt/seafile/seafile-data"
      }
    }
]
```

Probably it is possible to use different subfolders like /opt/seafile/seafile-data/fs, /opt/seafile/seafile-data/blocks, ...

**Comment by simonhammes** [comment]
If this is the case, the docs should also be updated.

https://manual.seafile.com/11.0/deploy_pro/multiple_storage_backends/#defining-storage-backends suggests:

```json
[
  {
    "storage_id": "cold_storage",
    "name": "Cold Storage",
    "is_default": false,
    "fs": {
      "backend": "fs",
      "dir": "/storage/seafile/seafile-data"
    },
    "commits": {
      "backend": "fs",
      "dir": "/storage/seafile/seafile-data"
    },
    "blocks": {
      "backend": "fs",
      "dir": "/storage/seafile/seaflle-data"
    }
  }
]
```

(ignore the typo for the blocks dir)

**Comment by simonhammes** [comment]
I was wrong. 

The JSON in the issue description is invalid: The quotes before `/opt/seafile/seafile-data` are missing!

BUT: The error message is totally stupid. If you fix the errors, it works. Seafile automatically creates `storage/{blocks,commits,fs}` subdirectories inside the configured directory. 

---

As a quick "fix", we can add a JSON syntax check to our entrypoint script if `SEAFILE__storage__storage_classes_file` is set to prevent errors like these.
