### ISSUE TITLE
Clarify what is missing for using redis

### ISSUE THREAD

**Issue by christophdb** [datamate-rethink-it/seafile-release#5]
## Django:

`SEAHUB__CACHE_BACKEND=redis` is not enough in docker-compose.yml. Redis package is missing in seafile docker container.

## memory cache:

> Since Pro Edition 11.0, both memcached and Redis can be used as memory cache.

in seafile.conf:
```
[redis]
# your redis server address
redis_server = 127.0.0.1
# your redis server port
redis_port = 6379
# size of connection pool to redis, default is 100
max_connections = 100
```

Strange, that it is configured like that. The message queue is configured likde this in seafevents.conf

```
[EVENTS PUBLISH]
enabled = false
## message format: repo-update\t{{repo_id}}}\t{{commit_id}}
## Currently only support redis message queue
mq_type = redis

[REDIS]
## redis use the 0 database and "repo_update" channel
server = 192.168.1.1
port = 6379
password = q!1w@#123
```

**Comment by christophdb** [comment]
Task is to clarify what is missing.

**Comment by simonhammes** [comment]
> ## Django:
> `SEAHUB__CACHE_BACKEND=redis` is not enough in docker-compose.yml. Redis package is missing in seafile docker container.
> 

Still an issue with 11.0.12 PE (`ModuleNotFoundError: No module named 'redis'`)

> ## memory cache:
> > Since Pro Edition 11.0, both memcached and Redis can be used as memory cache.
> 
> in seafile.conf:
> 
> ```
> [redis]
> # your redis server address
> redis_server = 127.0.0.1
> # your redis server port
> redis_port = 6379
> # size of connection pool to redis, default is 100
> max_connections = 100
> ```

Causes 

```
../common/obj-backend-s3.c(743): Failed to create object cache, memcache or redis group should be configured.
../common/block-backend-s3.c(1082): Failed to create object cache, memcache or redis group should be configured.
../common/obj-backend-s3.c(743): Failed to create object cache, memcache or redis group should be configured.
```

(using 11.0.12 PE)

**Comment by christophdb** [comment]
try "redist_host" instead of "redis_server" in seafile.conf

**Comment by simonhammes** [comment]
> try "redist_host" instead of "redis_server" in seafile.conf

`redis_host` works

11.0.14 contains the `redis` python package (required for seahub)
